name: Comic
options:
  xcodeVersion: "16.0"
packages:
  CustomUI:
    path: "Packages/CustomUI"
  DataBase:
    path: "Packages/DataBase"
  Detail:
    path: "Packages/Detail"
  EpisodePicker:
    path: "Packages/EpisodePicker"
  Extensions:
    path: "Packages/Extensions"
  Favorite:
    path: "Packages/Favorite"
  History:
    path: "Packages/History"
  Reader:
    path: "Packages/Reader"
  Search:
    path: "Packages/Search"
  Setting:
    path: "Packages/Setting"
  Update:
    path: "Packages/Update"
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 18.0
    SWIFT_VERSION: 6.0
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
targets:
  Comic:
    platform: iOS
    type: application
    sources:
      - Sources
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        INFOPLIST_FILE: Sources/App/Info.plist
        MARKETING_VERSION: 2.0.0
        CURRENT_PROJECT_VERSION: 20250305
        PRODUCT_BUNDLE_IDENTIFIER: com.shinrenpan.Comic
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
    dependencies:
      - package: CustomUI
      - package: Favorite
      - package: History
      - package: Setting
      - package: Update
