name: Comic
options:
  xcodeVersion: "16.0"
packages:
  CustomUI:
    path: "CustomUI"
  DataBase:
    path: "DataBase"
  Detail:
    path: "Detail"
  EpisodePicker:
    path: "EpisodePicker"
  Extensions:
    path: "Extensions"
  Favorite:
    path: "Favorite"
  History:
    path: "History"
  Reader:
    path: "Reader"
  Search:
    path: "Search"
  Setting:
    path: "Setting"
  Update:
    path: "Update"
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 18.0
    SWIFT_VERSION: 6.0
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
targets:
  Comic:
    platform: iOS
    type: application
    sources:
      - Sources
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        INFOPLIST_FILE: Sources/App/Info.plist
        MARKETING_VERSION: 2.0.0
        CURRENT_PROJECT_VERSION: 20250305
        PRODUCT_BUNDLE_IDENTIFIER: com.shinrenpan.Comic
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
    dependencies:
      - package: CustomUI
      - package: DataBase
      - package: Detail
      - package: EpisodePicker
      - package: Extensions
      - package: Favorite
      - package: History
      - package: Reader
      - package: Search
      - package: Setting
      - package: Update
